### ISSUE TITLE
I want to fetch data from my applications webservice/ servlet and project it using Alexa Skill

### ISSUE THREAD

**Issue by dhavaleneha** [alexa/skill-sample-java-fact#5]
I 've gone through most of the help documents but am unable to succeed in implementing the same. Any help?

**Comment by dhavaleneha** [comment]
Wrote a java class that implements RequestHandler and override canHandle and handle methods. Am I on the right track?

**Comment by pbheemag** [comment]
Hi @dhavaleneha ,
Could you kindly raise an issue using [this](https://github.com/alexa/alexa-skills-kit-sdk-for-java/issues/new) link. Providing more context would help us resolve your issue faster.

**Comment by dhavaleneha** [comment]
Hi,

Thanks for your reply. I have done the needful.

Regards,
Neha

**Comment by aszk** [comment]
Closing. Asked to raise an issue using the link.
